neuro/Notes/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField,TextAreaField
from wtforms.validators import DataRequired,Length,Email,EqualTo, ValidationError
from flask_wtf.file import FileField, FileAllowed

class NoteForm(FlaskForm):
    title = TextAreaField('Tytuł')
    text =  TextAreaField('Twoja notatka')
    submit = SubmitField('Zapisz')

neuro/Tests/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField,TextAreaField
from wtforms.validators import DataRequired,Length,Email,EqualTo, ValidationError
from flask_wtf.file import FileField, FileAllowed

class AnswerForm(FlaskForm):
    answer = TextAreaField('Odpowiedz',validators=[Length(max=255,message='Maksymalna ilość znaków to 255')])
    submit = SubmitField('Wyślij odpowiedź')

neuro/Admin/routes.py
from flask import render_template, url_for, flash, redirect,request,Blueprint
from neuro import app,db,bcrypt
from neuro.models import User,UserDay, Note, Day, DayText,Math
from neuro.Admin.forms import LoginForm, RegistrationForm, WordForm, AdminForm
from flask_login import login_user, current_user, logout_user,login_required
from sqlalchemy import text
from flaskext.mysql import pymysql
from functools import wraps
from sqlalchemy.sql import func
Admin = Blueprint('Admin',__name__)

ROWS_PER_PAGE=25

def admin_required(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if current_user.role == "admin":
            return f(*args, **kwargs)
        else:
            flash("You need to be an admin to view this page.")
            return redirect(url_for('Main.error'))

    return wrap
####### Main account page #######
@Admin.route("/admin",methods=['GET','POST'])
@login_required
@admin_required
def admin():
    users_number = User.query.filter_by(role="patient").count()
    page = request.args.get('page',1,type=int)
    users = User.query.order_by(User.created_at.desc()).paginate(page=page,per_page=ROWS_PER_PAGE)
    test_number = UserDay.query.count()
    average = db.session.query(func.avg(UserDay.score)).scalar()
    if request.method == 'POST':
        data = request.form["search"]
        search = "%{}%".format(data)
        users = User.query.filter(User.name.like(search)).paginate(page=page,per_page=ROWS_PER_PAGE)
    return render_template('admin/admin.html',users=users,users_number=users_number,test_number=test_number,average=average)

@Admin.route("/admin/user/<int:user_id>",methods=['GET','POST'])
@login_required
@admin_required
def user(user_id):
    words = request.args.get('words',1,type=int)
    memories = request.args.get('memories',1,type=int)
    numbers = request.args.get('numbers',1,type=int)
    notes = request.args.get('notes',1,type=int)

    user = User.query.filter_by(id=user_id).first()
    day = Day.query.join(UserDay, Day.id == UserDay.day_id).add_columns(Day.number,Day.id,UserDay.total,UserDay.text,UserDay.id,UserDay.score,UserDay.user_id,UserDay.created_at).filter(UserDay.user_id==user_id).paginate(page=words,per_page=10)
    if len(day.items) ==0:
        count_words = 0 
        note = Note.query.filter(Note.user_id==user.id).paginate(page=notes,per_page=3)
      
    else:
        days = [row for row in day.items[0]]
        count_words = DayText.query.filter_by(day_id=days[1]).count()    
        note = Note.query.filter(Note.user_id==user.id).paginate(page=notes,per_page=3)
    return render_template('admin/admin_user.html',day=day,page_number=user_id,user=user,note=note,count_words=count_words)

@Admin.route("/admin/add",methods=['GET','POST'])
@login_required
@admin_required
def addAdmin():
    form = RegistrationForm()
    message=None
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(name=form.name.data,phone=form.phone.data, email=form.email.data, password=hashed_password,confirmed=True, role=form.role.data)
        db.session.add(user)
        db.session.commit()
        message="Pomyślne dodano admina"
    return render_template('admin/add_admin.html',form=form,message=message)


@Admin.route("/admin/test", methods=['GET','POST'])
@login_required
@admin_required
def adminTest():
    day = Day.query.all()
    return render_template('admin/admin_test.html',day=day)



@Admin.route("/admin/test/words/<int:day_id>", methods=['GET','POST'])
@login_required
@admin_required
def editTest(day_id):
    form = WordForm()
    word = DayText.query.filter_by(day_id=day_id).all()
    math = Math.query.filter_by(day_id=day_id).all()
    message=None
    if request.method == 'POST':
        for words in word:
            data = request.form[str(words.id)]
            dayTexts = DayText.query.filter_by(id=words.id).update(dict(text=data.upper()))
            db.session.commit()
        for maths in math:
            data = request.form[str(maths.id)]
            mathematics = Math.query.filter_by(id=maths.id).update(dict(text=data.upper()))
            db.session.commit()
            message="Pomyślne zaktualizowano dzień"
    return render_template('admin/admin_words.html',word=word,math=math,form=form,day_id=day_id,message=message)

@Admin.route("/admin/add/words/<int:day_id>", methods=['GET','POST'])
@login_required
@admin_required
def addWords(day_id):
    word = DayText(text="Edytuj słowo",day_id=day_id)
    db.session.add(word)
    db.session.commit()
    return redirect(url_for("Admin.editTest",day_id=day_id))

@Admin.route("/admin/add/maths/<int:day_id>", methods=['GET','POST'])
@login_required
@admin_required
def addMath(day_id):
    math = Math(text="Edytuj zadanie",day_id=day_id)
    db.session.add(math)
    db.session.commit()
    return redirect(url_for("Admin.editTest",day_id=day_id))

@Admin.route("/admin/add/words/<int:day_id>/<int:word_id>/delete", methods=['GET','POST'])
@login_required
@admin_required
def deleteWords(day_id,word_id):
    word = DayText.query.filter_by(id=word_id).first()
    db.session.delete(word)
    db.session.commit()
    return redirect(url_for("Admin.editTest",day_id=day_id))

@Admin.route("/admin/answer/<int:user_day_id>/delete", methods=['GET','POST'])
@login_required
@admin_required
def deleteAnswer(user_day_id):
    word = UserDay.query.filter_by(id=user_day_id).first()
    db.session.delete(word)
    db.session.commit()
    return redirect(url_for("Admin.user",user_id=word.user_id))

@Admin.route("/admin/add/maths/<int:day_id>/<int:math_id>/delete", methods=['GET','POST'])
@login_required
@admin_required
def deleteMaths(day_id,math_id):
    math = Math.query.filter_by(id=math_id).first()
    db.session.delete(math)
    db.session.commit()
    return redirect(url_for("Admin.editTest",day_id=day_id))

@Admin.route("/admin/messages", methods=['GET','POST'])
@login_required
@admin_required
def messages():
    page = request.args.get('page',1,type=int)
    users = User.query.order_by(User.created_at.desc()).paginate(page=page,per_page=ROWS_PER_PAGE)
    return render_template('admin/messages.html',users=users)

neuro/Main/routes.py
from flask import render_template, url_for, flash, redirect,request,Blueprint
from neuro import app,db,bcrypt
from neuro.models import User
from flask_login import login_user, current_user, logout_user,login_required


Main = Blueprint('Main',__name__)


@Main.route('/')
def index():
    error=None  
    return render_template('main.html',error=error) 




@Main.errorhandler(404)
def page_not_found(e):
    return render_template('main/404.html'), 404

@Main.route('/404')
def error():
    return render_template('main/404.html')

neuro/Notes/routes.py
from flask import render_template, url_for, flash, redirect,request,Blueprint
from neuro import app,db,bcrypt
from neuro.models import User, Day, Note
from neuro.Notes.forms import NoteForm
from flask_login import login_user, current_user, logout_user,login_required
from sqlalchemy import text

Notes = Blueprint('Notes',__name__)
ROWS_PER_PAGE=3
####### Main Notes page #######
@Notes.route("/notes",methods=['GET','POST'])
@login_required
def notes():
    page = request.args.get('page',1,type=int)
    note = Note.query.filter(Note.user_id==current_user.id).order_by(Note.updated_at.desc()).paginate(page=page,per_page=ROWS_PER_PAGE)
    return render_template("panel/notes.html",note=note)
    

@Notes.route("/notes/add",methods=['GET','POST'])
@login_required
def addNotes():
    form = NoteForm()
    if form.validate_on_submit():
        note = Note(title=form.title.data, text=form.text.data, user_id=current_user.id)
        db.session.add(note)
        db.session.commit()
        message = "Odpowiedz została wysłana!"
        return redirect(url_for('Notes.notes'))
    return render_template("panel/add_notes.html",form=form)

@Notes.route("/notes/<int:note_id>",methods=['GET','POST'])
@login_required
def editNotes(note_id):
    note = Note.query.get_or_404(note_id)
    form = NoteForm()
    if form.validate_on_submit():
        note = Note.query.filter_by(id=note_id).update(dict(title=form.title.data, text=form.text.data))
        db.session.commit()
        return redirect(url_for('Notes.notes'))
    note_sql = db.engine.execute(text("SELECT title,text FROM note WHERE id = :id ").execution_options(autocommit=True),{'id': note_id})
    for notes in note_sql:
        print(notes[0])
    form.title.default = notes[0]
    form.text.default = notes[1]
    form.process()
    return render_template("panel/edit_note.html",note=note, form=form,title=notes[0])

@Notes.route("/notes/<int:note_id>/delete", methods=['GET','POST'])
@login_required
def deleteNotes(note_id):    
    note = Note.query.filter_by(id=note_id).first()
    db.session.delete(note)
    db.session.commit()
    return redirect(url_for('Notes.notes'))

neuro/Tests/routes.py
from flask import render_template, url_for, flash, redirect,request,Blueprint,json
from neuro import app,db,bcrypt
from neuro.models import User, Day, UserDay, DayText
from neuro.Tests.forms import AnswerForm
from flask_login import login_user, current_user, logout_user,login_required
from sqlalchemy import text
import re

Tests = Blueprint('Tests',__name__)

####### Main Tests page #######
@Tests.route("/tests",methods=['GET','POST'])
@login_required
def tests():
    day = Day.query.all()
    return render_template('tests/tests.html', day=day)
    
@Tests.route("/tests/words",methods=['GET','POST'])
@login_required
def words():
    day = Day.query.all()
    return render_template('tests/words.html', day=day)

@Tests.route("/tests/words/<int:day_id>",methods=['GET','POST'])
@login_required
def day(day_id):
    day = Day.query.get_or_404(day_id)
    form = AnswerForm()
    message=None
    daytextSql = db.engine.execute(text("SELECT text FROM day_text WHERE day_id = :id ").execution_options(autocommit=True),{'id': day_id})
    dayTexts = [list(row) for row in daytextSql]
    mathSql = db.engine.execute(text("SELECT text FROM math WHERE day_id = :id ").execution_options(autocommit=True),{'id': day_id})
    maths = [list(row) for row in mathSql]
    correct = DayText.query.filter_by(day_id=day_id).all()
    total = DayText.query.filter_by(day_id=day_id).count()
    correct_words =[]
    for corrects in correct:
        correct_words.append(corrects.text)
    
    if form.validate_on_submit():
        data = form.answer.data.upper()
        words = re.findall(r"[\w']+",data)
        a = set(words)
        b = set(correct_words)
        score = len(a&b)
       
        answer = UserDay(text=data, score=score,total=total, user_id=current_user.id, day_id=day_id)
        db.session.add(answer)
        db.session.commit()
        message = "Odpowiedź została wysłana!"
    return render_template('tests/day.html', day=day,message=message,form=form,dayTexts=json.dumps(dayTexts,ensure_ascii=False),maths=json.dumps(maths,ensure_ascii=False))


@Tests.route("/tests/numbers",methods=['GET','POST'])
@login_required
def numbers():
    return render_template('tests/numbers.html')


@Tests.route("/tests/memory",methods=['GET','POST'])
@login_required
def memory():
    return render_template('tests/memory.html')

neuro/templates/add_admin.html
{% extends "admin.html" %}
{% block content %}

<style>
::placeholder{
  color:white !important;
}
.select1{
  border-radius:10px !important;
}
.select1:hover{
  background-color:rgb(108, 102, 251)!important;
}
.is-active2{
  background-color:rgb(108, 102, 251)!important;
}


</style>
{%if message%}
<div class="box has-background-primary"><p class="has-text-white">{{message}}</p></div>
{%endif%}
<section class="section main-content columns is-fullheight">

<div class="container column is-10">
    <div class="box"style="border-radius:4px;background-color:rgb(35, 37, 56);  ">
        
        <div class="field">
            <h1 class="has-text-centered-mobile is-uppercase has-text-weight-bold is-size-3 has-text-primary">Dodaj admina</h1>
            <form method="POST" action="">
                {{form.hidden_tag()}}
                {% if form.email.errors %}
            <p class="control has-icons-left has-icons-right has-text-danger">
              {{ form.email(class="input",style="border:none;outline:none;border-bottom:1px solid white;border-radius:0px; background-color:rgb(35, 37, 56); color:white;", placeholder="Email*")}}
              <span class="icon is-small is-left">
                <i class="fas fa-envelope"></i>
              </span>
              
            </p>
            {% for error in form.email.errors %}
                <span><strong class="has-text-danger">{{ error }}</strong></span>
              {% endfor %}
            {% else %}
            <p class="control has-icons-left has-icons-right">
                {{ form.email(class="input",style="border:none;outline:none;border-bottom:1px solid white;border-radius:0px; background-color:rgb(35, 37, 56); color:white;", placeholder="Email*")}}
                <span class="icon is-small is-left">
                  <i class="fas fa-envelope"></i>
                </span>
            {% endif %}
          </div>
          <div class="field">
            <p class="control has-icons-left">
                {{ form.name(class="input",style="border:none;outline:none;border-bottom:1px solid white;border-radius:0px; background-color:rgb(35, 37, 56); color:white;", placeholder="Imię i nazwisko*")}}
              <span class="icon is-small is-left">
                <i class="fas fa-user"></i>
              </span>
            </p>
          </div>
          <div class="field">
            <p class="control has-icons-left">
                {{ form.phone(class="input",style="border:none;outline:none;border-bottom:1px solid white;border-radius:0px; background-color:rgb(35, 37, 56); color:white;", placeholder="Numer telefonu: +48666777888")}}
              <span class="icon is-small is-left">
                <i class="fas fa-phone"></i>
              </span>
            </p>
          </div>
    
          <div class="field">
            {% if form.password.errors %}
            <p class="control has-icons-left">
                {{ form.password(class="input",style="border:none;outline:none;border-bottom:1px solid white;border-radius:0px; background-color:rgb(35, 37, 56); color:white;", placeholder="Hasło*")}}
              <span class="icon is-small is-left">
                <i class="fas fa-lock"></i>
              </span>
            </p>
            {% for error in form.password.errors %}
                <span><strong class="has-text-danger">{{ error }}</strong></span>
            {% endfor %}
            {% else %}
            <p class="control has-icons-left has-icons-right">
                {{ form.password(class="input",style="border:none;outline:none;border-bottom:1px solid white;border-radius:0px; background-color:rgb(35, 37, 56); color:white;", placeholder="Hasło*")}}
                <span class="icon is-small is-left">
                  <i class="fas fa-lock"></i>
                </span>
            {% endif %}
          </div>
          <div class="field">
            {% if form.confirm_password.errors %}
            <p class="control has-icons-left">
                {{ form.confirm_password(class="input",style="border:none;outline:none;border-bottom:1px solid white;border-radius:0px; background-color:rgb(35, 37, 56); color:white;", placeholder="Hasło Raz Jeszcze*")}}
              <span class="icon is-small is-left">
                <i class="fas fa-lock"></i>
              </span>
            </p>
            {% for error in form.confirm_password.errors %}
                <span><strong class="has-text-danger">{{ error }}</strong></span>
            {% endfor %}
            {% else %}
            <p class="control has-icons-left has-icons-right">
                {{ form.confirm_password(class="input",style="border:none;outline:none;border-bottom:1px solid white;border-radius:0px; background-color:rgb(35, 37, 56); color:white;", placeholder="Hasło Raz Jeszcze*")}}
                <span class="icon is-small is-left">
                  <i class="fas fa-lock"></i>
                </span>
            {% endif %}
           
          </label>
         
          {%if error%}
          <p><strong class="has-text-danger">{{ error }}</strong></p>
          {%endif%}
          </div>
          {{ form.submit(class="button is-danger",style="background-color:rgb(108, 102, 251);",type="submit")}}
          
        </form>
        
</div>
</div>
</section>




{% endblock content %}

neuro/templates/add_notes.html
{% extends "main.html" %}
{% block content1 %}
<section class="section has-text-centered" style="margin:25px; positon:center;background-color:rgb(35, 37, 56); color:black ">

<form method="POST" action="">
                 {{form.hidden_tag()}}
             <p class="title has-text-primary">Tytuł</p>
              {{ form.title(class="input", style="border:none; color:black;", placeholder="Tytuł")}}
           
              <p class="title has-text-primary"style="margin-top:20px;">Treść</p>
              {{ form.text(class="input", style="border:none; color:black; height:200px;", placeholder="Tekst")}}
           {{ form.submit(class="button is-primary",style="margin-top:25px;font-weight:700",type="submit")}}
</form>
</section>



{% endblock content1 %}
{% block content %}
{% endblock content %}

neuro/templates/admin.html
<!DOCTYPE html>
<html style="background-color: transparent" >
   <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta charset="utf-8">
      <meta name="keywords" content="Neuromedical, Alzhaimer, Tests">
      <meta name="description" content="Online testy psychologiczne">
      <title>Neuromedical | Panel Admina</title>
      <link rel="stylesheet" href="{{ url_for('static', filename='css/bulma.css') }}"media="screen">
      <link rel="stylesheet" href="{{ url_for('static', filename='fontawesome/css/all.css') }}"media="screen">
      <script defer src="{{url_for('static', filename='fontawesome/js/all.js')}}"></script>
      <link rel="preconnect" href="https://fonts.gstatic.com">
      <link href="https://fonts.googleapis.com/css2?family=Noto+Sans&display=swap" rel="stylesheet">
   </head>
   <style>
      @media screen and (max-width: 1068px) {
      #menu-toggle:checked + .nav-menu {
      display: block;
      }
      }
      .table-wrapper{
      overflow-x:auto;
      }
      .table-wrapper::-webkit-scrollbar-track{
      background-color:black;
      }
      .table-wrapper::-webkit-scrollbar-thumb{
      background-color:black;
      }
      .select1{
      border-radius:10px !important;
      }
      .select1:hover{
      background-color:rgb(108, 102, 251)!important;
      }
      .is-active2{
      background-color:rgb(108, 102, 251)!important;
      }
      .dodaj:hover{
      background:none;
      }
            .navbar-link:hover{
      background-color:gray !important;
      }
      .navbar-link{
      transition:0.5s ease !important;
      }
      .navbarlinks{
      transition:0.5s ease !important;
      }
      .navbarlinks:hover {
      background-color:rgb(108, 102, 251) !important;
      color:white !important;
      }
      .navbarlinkslogout{
      transition:0.5s ease !important;
      color: red !important;
      }
      .navbarlinkslogout:hover {
      background-color:red !important;
      color:white !important;
      }
      .navbar-dropdown{
      transition:0.2s ease !important;
      }
      .simple{
        margin:10px;
        border-radius:4px;
        transition:0.2s ease !important;
        
      }
      .simple:hover{
        background:none !important;
        color:rgb(108, 102, 251) !important;
      }
   </style>
   <body style="background-color: rgb(47, 46, 75);color:white;padding:10px;">
      <nav class="navbar" role="navigation" aria-label="main navigation" style="margin:20px; border-radius:10px; background:transparent;border-radius:4px; color:white;background-color:rgb(35, 37, 56);"aria-label="menu" aria-expanded="false" data-target="menu">
         <div class="navbar-brand">
            <a class="navbar-item" href="/admin">
               <h1 class="text has-text-white"><strong>Neuromedical | Panel Admina </strong></h1>
            </a>
            <a role="button" class="navbar-burger" style="color:white; border-radius:25px;background-color:rgb(35, 37, 56)" aria-label="menu" aria-expanded="false" data-target="menu">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            </a>
         </div>
         <div id="menu" class="navbar-menu" style="color:white; border-radius:4px;background-color:transparent;">
            <div class="navbar-start">
               <a class="navbar-item has-text-white simple" href="/admin">
               Lista
               </a>
               <div class="navbar-item  is-hoverable">
                  <a class="navbar-link has-text-white dodaj" style="border-radius:4px; color:white;background-color:rgb(35, 37, 56);" >
                  <i class="fas fa-tools" style="color:white;"></i>&nbsp; Narzędzia</a>
                  <div class="navbar-dropdown" style="border-radius:4px;border-top:none;background-color: rgba(255, 255, 255, .15);backdrop-filter: blur(5px);">
                     <a class="navbar-item has-text-white navbarlinks" href="/admin/test">
                     Edycja testu
                     </a>
                     <a class="navbar-item has-text-white navbarlinks" href="/admin/add">
                     Dodaj admina
                     </a>
                  </div>
               </div>
              
            </div>
             <div class="navbar-end">
          
            <div class="navbar-item">
            <div class="navbar-item  is-hoverable">
               <a class="navbar-link " style="border-radius:4px; color:white;background-color:rgb(35, 37, 56);">
               <i class="fas fa-user" ></i> &nbsp; {{current_user.name}}</a>
               <div class="navbar-dropdown" style="border-radius:4px;border-top:none;background-color: rgba(255, 255, 255, .15);  
                  backdrop-filter: blur(5px);">
                  <a class="navbar-item navbarlinks has-text-white" style="border:none;"  href="/admin/edit">
                  🎛&nbsp; Twoje dane
                  </a>
                  <a class="navbar-item navbarlinks  has-text-white"  href="/admin/notification">
                  🚨&nbsp; Powiadomienia
                  </a>
                  <hr class="navbar-divider" style="margin:10px;">
                   <a class="navbar-item navbarlinks has-text-white " href="/documentation/overview/start/">
               Pomoc
               </a>
                  <a class="navbar-item navbarlinkslogout" style="border-radius:4px;" href="/logout">
                  Wyloguj się
                  </a>
               </div>
            </div>
         </div>
         </div>

         </div>
         </div>
      </nav>
      {% block content %}
      <section class="main-content columns is-fullheight">
      
         <div class="container column is-10">
         <div class="section">
            <div class="container">
               <h2 class="title has-text-primary">List pacjentów</h2>
               <div class="columns has-text-centered">
                  <div class="column is-3">
                     <div class="box has-background-primary">
                        <h3 class="title is-2 has-text-white">448</h3>
                        <p class="subtitle has-text-white">Liczba pacjnetów</p>
                     </div>
                  </div>
                  <div class="column is-3">
                     <div class="box has-background-success">
                        <h3 class="title is-2 has-text-white">81</h3>
                        <p class="subtitle has-text-white">Rozwiązane testy</p>
                     </div>
                  </div>
                  <div class="column is-3">
                     <div class="box has-background-danger has-text-white">
                        <h3 class="title is-2 has-text-white">208</h3>
                        <p class="subtitle has-text-white">Uwagi</p>
                     </div>
                  </div>
               </div>
             
                <div class="field">
                <form class="form has-text-white" method="post" action="" 
         >
           <div class="columns">
          <div class="column">
    <input type="text" class="input" placeholder="Szukaj pacjenta" name="search" style="border:none;outline:none;border-radius:0px; background-color:rgb(35, 37, 56); color:white;">
          </div>
             <div class="column">
            <button class="button"  type="submit"><i class="fa fa-search"></i>&nbsp; Szukaj
            </button>
              </div>
            </div>
        </form>
        </div>
               <div class="table-wrapper">
                  <table class="table is-fullwidth" style="overflow-x:scroll;background-color:rgb(35, 37, 56);color:white;border-radius:10px; padding:20px;">
                     <thead style="color:white; overflow:scroll;">
                        <tr >
                           <th scope="col"style="color:white; ">ID #</th>
                           <th scope="col"style="color:white;">Nazwa</th>
                           <th scope="col"style="color:white;">Email</th>
                           <th scope="col"style="color:white;">Rola</th>
                           <th class="has-text-centered  has-text-white" scope="col">Data dołączenia</th>
                           <th class="has-text-centered has-text-white" scope="col">Zobacz</th>
                        </tr>
                     </thead>
                     <tbody >
                        {% for user in users.items%}
                        <tr>
                           <td>{{loop.index}}</td>
                           <td>
                              <a href="/admin/user/{{user.id}}">
                                 <div class="media">
                                    <div class="media-content">{{user.name}}</div>
                                 </div>
                              </a>
                           </td>
                           <td><a class="has-text-info"href="mailto:{{user.email}}">{{user.email}}</a></td>
                           <td>{{user.role}}</td>
                           <td class="has-text-centered has-text-primary">{{user.created_at}}</td>
                           <td class="has-text-centered "><a class="has-text-warning is-hoverable" href="/admin/user/{{user.id}}">🔍</a></td>
                        </tr>
                        {% endfor %}
                     </tbody>
                  </table>
               </div>
            </div>
         </div>
         <nav style="margin:25px;">
            <div class="container">
            <div class="pagination" role="navigation" aria-label="pagination">
               <div class="lol">
                  <a  href="{{ url_for('Admin.admin', page=users.prev_num) }}"
                     class="button is-danger
                     {% if users.page == 1 %}is-hidden{% endif %}">
                  &laquo;
                  </a>
                  <!-- Loop through the number of pages to display a link for each-->
                  {% for page_num in users.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                  {% if page_num %}
                  <!-- Check for the active page and set the link to "Active"-->
                  {% if users.page == page_num %}
                  <a style="background-color:rgb(108, 102, 251)"href="{{ url_for('Admin.admin', page=page_num) }}"
                     class="button has-text-white is-active">
                  {{ page_num }}
                  </a>
                  {% else %}
                  <a href="{{ url_for('Admin.admin', page=page_num) }}"
                     class="button">
                  {{ page_num }}
                  </a>
                  {% endif %}
                  {% else %}
                  ...
                  {% endif %}
                  {% endfor %}
                  <a href="{{ url_for('Admin.admin', page=users.next_num) }}"
                     class="button is-danger
                     {% if users.page == users.pages %}disabled{% endif %}">
                  &raquo;
                  </a>
               </div>
            </div>
         </nav>
      </section>
      {% endblock content %}
      <script>
         document.addEventListener('DOMContentLoaded', function () {
         
           // Get all "navbar-burger" elements
           var $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
           var $navbarLinks   = Array.prototype.slice.call(document.querySelectorAll('.navbar-link'),0);
            var $navbarDrop   = Array.prototype.slice.call(document.querySelectorAll('.navbar-dropdown'),0);
           // Check if there are any nav burgers
           if ($navbarBurgers.length > 0) {
         
             // Add a click event on each of them
             $navbarBurgers.forEach(function ($el) {
               $el.addEventListener('click', function () {
         
                 // Get the target from the "data-target" attribute
                 var target = $el.dataset.target;
                 var $target = document.getElementById(target);
         
                 // Toggle the class on both the "navbar-burger" and the "navbar-menu"
                 $el.classList.toggle('is-active');
                 $target.classList.toggle('is-active');
         
               });
             });
         
             $navbarLinks.forEach(function ($el) {
               $el.addEventListener('click', function () {
         
                 // Get the target from the "data-target" attribute
                 
                 var $target = document.getElementByID('navbar1');
         
                 // Toggle the class on both the "navbar-burger" and the "navbar-menu"
                 $el.classList.toggle('is-active');
                 $target.classList.toggle('is-hidden-mobile');
         
               });
             });
           }
         
         });
         
         
         
         
      </script>
   </body>
</html>

neuro/templates/email.html
{% extends "main.html" %}
{% block content %}
<section class="section">
<div class="box">
<p>Welcome! Thanks for signing up. Please follow this link to activate your account:</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br>
<p>Cheers!</p>
</div>
</section>
{%endblock content%}